version: "3.9"
services:
  web:
    build: .
    ports:
      - "8888:8888"
  couchbase:
    image: couchbase:enterprise
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210